import './globals.css';
import type { Metadata } from 'next';
import { PT_Sans } from 'next/font/google';

import { Providers } from '../../redux/provider';
import { Locale, i18n } from '@/i18n-config';

const ptSans = PT_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <Providers>
      <html lang={params.lang} className={ptSans.className}>
        <body>
          <main>{children}</main>
        </body>
      </html>
    </Providers>
  );
}
